module.exports = {
  data: [
    {
      question: "Who was the wife of Lord Rama?",
      option1: "Draupadi",
      option2: "Radha",
      option3: "Sita",
      option4: "Rukmini",
      ans: 3,
    },
    {
      question: "Who led the Pandavas in the Kurukshetra War?",
      option1: "Krishna",
      option2: "Yudhishthira",
      option3: "Arjuna",
      option4: "Bhima",
      ans: 3,
    },
    {
      question: "Who was swallowed by a giant fish according to Indian mythology?",
      option1: "Savitri",
      option2: "Ganga",
      option3: "Bhima",
      option4: "None",
      ans: 4, // Not directly analogous in Indian mythology.
    },
    {
      question: "Who killed Ravana?",
      option1: "Karna",
      option2: "Bhima",
      option3: "Krishna",
      option4: "Rama",
      ans: 4,
    },
    {
      question: "Who was abandoned as a child in a river?",
      option1: "Karna",
      option2: "Arjuna",
      option3: "Bhishma",
      option4: "Krishna",
      ans: 1,
    },
    {
      question: "Who was the first king of the Chandravamsha dynasty?",
      option1: "Pururavas",
      option2: "Yayati",
      option3: "Bharata",
      option4: "Vikramaditya",
      ans: 1,
    },
    {
      question: "Who interpreted dreams in Mahabharata?",
      option1: "Vyasa",
      option2: "Vidura",
      option3: "Krishna",
      option4: "Narada",
      ans: 2,
    },
    {
      question: "Who built the bridge to Lanka?",
      option1: "Vishwakarma",
      option2: "Hanuman",
      option3: "Sugriva",
      option4: "Nala and Neela",
      ans: 4,
    },
    {
      question: "Who was cursed to be reborn as a demon?",
      option1: "Jaya and Vijaya",
      option2: "Yama",
      option3: "Kashyapa",
      option4: "Shiva",
      ans: 1,
    },
    {
      question: "Who is known as the strongest warrior in Mahabharata?",
      option1: "Duryodhana",
      option2: "Bhima",
      option3: "Karna",
      option4: "Arjuna",
      ans: 2,
    },
    {
      question: "Who was born from a lotus from Vishnu's navel?",
      option1: "Shiva",
      option2: "Brahma",
      option3: "Indra",
      option4: "Agni",
      ans: 2,
    },
    {
      question: "Who was the eldest Pandava?",
      option1: "Arjuna",
      option2: "Yudhishthira",
      option3: "Bhima",
      option4: "Nakula",
      ans: 2,
    },
    {
      question: "Who wrote the Mahabharata?",
      option1: "Valmiki",
      option2: "Vishwamitra",
      option3: "Vyasa",
      option4: "Agastya",
      ans: 3,
    },
    {
      question: "Who was the first man according to Hindu mythology?",
      option1: "Manu",
      option2: "Swayambhuva",
      option3: "Yama",
      option4: "Narada",
      ans: 1,
    },
    {
      question: "Who was known for his wisdom and impartiality?",
      option1: "Krishna",
      option2: "Vidura",
      option3: "Karna",
      option4: "Dronacharya",
      ans: 2,
    },
    {
      question: "Who built the city of Dwarka?",
      option1: "Indra",
      option2: "Shiva",
      option3: "Krishna",
      option4: "Varuna",
      ans: 3,
    },
    {
      question: "Who cursed King Pandu to die if he touched his wives?",
      option1: "Rishi Durvasa",
      option2: "Rishi Kindama",
      option3: "Rishi Gautama",
      option4: "Rishi Parashara",
      ans: 2,
    },
    {
      question: "Who was the son of Vayu and known for his strength?",
      option1: "Hanuman",
      option2: "Bhima",
      option3: "Arjuna",
      option4: "Krishna",
      ans: 1,
    },
    {
      question: "Who transformed into a pillar of light to settle a dispute?",
      option1: "Vishnu",
      option2: "Shiva",
      option3: "Brahma",
      option4: "Agni",
      ans: 2,
    },
    {
      question: "Who is called the 'Father of All Gods' in Hinduism?",
      option1: "Shiva",
      option2: "Indra",
      option3: "Brahma",
      option4: "Vishnu",
      ans: 3,
    },
    {
      question: "Who fought against an incarnation of Vishnu as Narasimha?",
      option1: "Kamsa",
      option2: "Hiranyakashipu",
      option3: "Ravana",
      option4: "Vritra",
      ans: 2,
    },
    {
      question: "Who is known as the goddess of learning?",
      option1: "Lakshmi",
      option2: "Durga",
      option3: "Saraswati",
      option4: "Parvati",
      ans: 3,
    },
    {
      question: "Who was reborn as Lord Krishna's brother?",
      option1: "Balarama",
      option2: "Yudhishthira",
      option3: "Bhishma",
      option4: "Duryodhana",
      ans: 1,
    },
    {
      question: "Who was cursed to live a thousand lifetimes as a snake?",
      option1: "Ravana",
      option2: "Nahusha",
      option3: "Vishwamitra",
      option4: "Agastya",
      ans: 2,
    },
    {
      question: "Who was the sage that tested King Harishchandra’s truthfulness?",
      option1: "Narada",
      option2: "Vishwamitra",
      option3: "Valmiki",
      option4: "Parashurama",
      ans: 2,
    },
    {
      question: "Who was the queen who performed a sacrifice for a child?",
      option1: "Kaikeyi",
      option2: "Kunti",
      option3: "Gandhari",
      option4: "Satyavati",
      ans: 3,
    },
    {
      question: "Who was Lord Krishna's childhood friend and devotee?",
      option1: "Sudama",
      option2: "Arjuna",
      option3: "Karna",
      option4: "Bhima",
      ans: 1,
    },
    {
      question: "Who was known as the demon king who ruled Lanka?",
      option1: "Kumbhakarna",
      option2: "Bali",
      option3: "Ravana",
      option4: "Shurpanakha",
      ans: 3,
    },
    {
      question: "Who helped Krishna as his charioteer in the Mahabharata war?",
      option1: "Yudhishthira",
      option2: "Arjuna",
      option3: "Bhishma",
      option4: "Dronacharya",
      ans: 2,
    },
    {
      question: "Who was the blind king in the Mahabharata?",
      option1: "Yudhishthira",
      option2: "Dhritarashtra",
      option3: "Shantanu",
      option4: "Pandu",
      ans: 2,
    },
    {
      question: "Who was the river goddess who married King Shantanu?",
      option1: "Ganga",
      option2: "Yamuna",
      option3: "Saraswati",
      option4: "Godavari",
      ans: 1,
    },
    {
      question: "Who was the half-human, half-eagle deity in Hindu mythology?",
      option1: "Naga",
      option2: "Garuda",
      option3: "Hanuman",
      option4: "Jatayu",
      ans: 2,
    },
    {
      question: "Who was cursed to become a stone by Rishi Gautama?",
      option1: "Lakshmi",
      option2: "Sita",
      option3: "Ahilya",
      option4: "Draupadi",
      ans: 3,
    },
    {
      question: "Who is the Hindu god of love?",
      option1: "Indra",
      option2: "Kama",
      option3: "Shiva",
      option4: "Varuna",
      ans: 2,
    },
    {
      question: "Who was the teacher of both the Pandavas and Kauravas?",
      option1: "Bhishma",
      option2: "Dronacharya",
      option3: "Kripacharya",
      option4: "Shalya",
      ans: 2,
    },
    {
      question: "Who was known as the remover of obstacles?",
      option1: "Krishna",
      option2: "Vishnu",
      option3: "Shiva",
      option4: "Ganesha",
      ans: 4,
    },
    {
      question: "Who killed the demon Mahishasura?",
      option1: "Lakshmi",
      option2: "Durga",
      option3: "Kali",
      option4: "Saraswati",
      ans: 2,
    },
  ]
};

